### PR TITLE
Added Coveralls dependencies

### PR DESCRIPTION
**Pull request by lslezak**

### CODE REVIEW

**Comment by mvidner** [comment]
LGTM

**Comment by lslezak** [comment]
JFYI: I have added the dependencies directly to the `coveralls` gem as @jreidinger suggested (
https://build.opensuse.org/request/show/305604).

I'll close this PR if the SR is accepted to `devel:languages:ruby:extensions` project.

**Comment by jreidinger** [comment]
@lslezak I accept SR

**Comment by lslezak** [comment]
@jreidinger thanks, I'm closing this PR, it has been fixed in the [coveralls RPM package in d:l:r:e](https://build.opensuse.org/package/show/devel:languages:ruby:extensions/rubygem-coveralls)

**Pull request closed without merging**
