### PR TITLE
Fix build with multiple Ruby instances

### PR DESCRIPTION
**Pull request by lslezak**
Use the system default `rake` for running the tests during RPM build.

### CODE REVIEW

**Comment by lslezak** [comment]
Small cheat: I have already committed this change to [YaST:Head/rubygem-yast-rake-ci](https://build.opensuse.org/package/show/YaST:Head/rubygem-yast-rake-ci) to verify it really builds for all targets.  It does :wink:

**Comment by mvidner** [comment]
Ah, that's nice! Except the commit message does not seem to make sense: I understand "system default rake" as `/usr/bin/rake` which we tried before and that did not work. Now we are using "rake for the particular version of Ruby that we are building the gem for", right?

**Comment by lslezak** [comment]
Updated the commit message.

**Comment by mvidner** [comment]
Thanks, LGTM!

**Pull request merged**
